<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        gc_collect_cycles();
    }
}
